# Generated by Django 5.1.13 on 2025-11-11 07:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('cupo', models.PositiveIntegerField()),
                ('precio', models.FloatField()),
                ('requiere_material', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Camping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(max_length=200)),
                ('estrellas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sitio_web', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('es_staff', models.BooleanField(default=False)),
                ('rol', models.CharField(choices=[('recepcionista', 'Recepcionista'), ('cuidador', 'Cuidador')], max_length=20)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('telefono', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descripcion', models.TextField(blank=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('capacidad', models.PositiveIntegerField(default=2)),
                ('tiene_sombra', models.BooleanField(default=False)),
                ('camping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camping.camping')),
            ],
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=50)),
                ('disponible_de_noche', models.BooleanField(default=False)),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='camping.perfilusuario')),
            ],
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='datos_usuario',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='camping.persona'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(blank=True, max_length=30, null=True)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('acepta_publicidad', models.BooleanField(default=False)),
                ('datos_cliente', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='camping.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_alta', models.DateField()),
                ('turno', models.CharField(choices=[('ma', 'Mañana'), ('ta', 'Tarde')], max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='camping.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('actividades', models.ManyToManyField(related_name='actividades', to='camping.actividad')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='camping.cliente')),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camping.parcela')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField(default=1)),
                ('observaciones', models.CharField(blank=True, max_length=150, null=True)),
                ('reserva_asociada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='camping.reserva')),
                ('servicios_extra', models.ManyToManyField(to='camping.serviciosextra')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('emitida_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('pagado', models.BooleanField(default=False)),
                ('reserva_extra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='camping.reservaextras')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('coche', 'Coche'), ('moto', 'Moto'), ('caravana', 'Caravana')], max_length=50)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('peso', models.FloatField(help_text='Introduce el peso aproximado en Kilogramos')),
                ('marca', models.CharField(max_length=25, null=True)),
                ('cliente', models.ManyToManyField(related_name='vehiculos', to='camping.cliente')),
            ],
        ),
    ]
