# Generated by Django 5.1.13 on 2025-12-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
