# Generated by Django 5.1.13 on 2025-10-24 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='datos_cliente',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='camping.persona'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='datos_usuario',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='camping.persona'),
        ),
        migrations.CreateModel(
            name='ReservaExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField(default=1)),
                ('observaciones', models.CharField(blank=True, max_length=150, null=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='camping.reserva')),
                ('servicios_extra', models.ManyToManyField(to='camping.serviciosextra')),
            ],
        ),
        migrations.AlterField(
            model_name='factura',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='camping.reservaextras'),
        ),
        migrations.DeleteModel(
            name='ReservaExtra',
        ),
    ]
