# Generated by Django 5.1.13 on 2025-12-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='defaults/foto_perfil_base.png', null=True, upload_to='perfiles/'),
        ),
    ]
