# Generated by Django 5.1.13 on 2025-10-11 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='peso_kg',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='peso',
            field=models.FloatField(default=False, help_text='Introduce el peso aproximado en Kilogramos'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='emitida_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
