# Generated by Django 5.1.13 on 2025-10-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0002_remove_vehiculo_peso_kg_vehiculo_peso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='peso',
            field=models.FloatField(help_text='Introduce el peso aproximado en Kilogramos'),
        ),
    ]
