# Generated by Django 5.1.13 on 2025-10-24 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0002_alter_cliente_datos_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='parcela',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='camping.parcela'),
        ),
    ]
