# Generated by Django 5.1.13 on 2025-12-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0002_alter_perfilusuario_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('recepcionista', 'Recepcionista'), ('cuidador', 'Cuidador'), ('cliente', 'Cliente')], max_length=20, null=True),
        ),
    ]
