# Generated by Django 5.1.13 on 2025-12-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0002_perfilusuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('recepcionista', 'Recepcionista'), ('cuidador', 'Cuidador'), ('cliente', 'Cliente')], default='cliente', max_length=20),
        ),
    ]
