# Generated by Django 5.1.13 on 2025-10-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0003_alter_reserva_parcela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='actividades',
            field=models.ManyToManyField(related_name='actividades', to='camping.actividad'),
        ),
    ]
