# Generated by Django 5.1.13 on 2025-10-11 17:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0003_alter_vehiculo_peso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre_completo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='persona',
        ),
        migrations.AddField(
            model_name='cliente',
            name='acepta_publicidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='datos_cliente',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='camping.persona'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_cuenta',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='datos_usuario',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='camping.persona'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='username',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.CharField(default='', max_length=20),
        ),
    ]
