# Generated by Django 5.1.13 on 2025-12-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0003_alter_perfilusuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
