# Generated by Django 5.1.13 on 2025-10-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0004_remove_cliente_email_remove_cliente_nombre_completo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
