# Generated by Django 5.1.13 on 2025-10-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0005_vehiculo_marca'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Extra',
            new_name='ServiciosExtra',
        ),
    ]
