# Generated by Django 5.1.13 on 2025-10-11 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0006_rename_extra_serviciosextra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservaextra',
            old_name='extra',
            new_name='servicios_extra',
        ),
    ]
