# Generated by Django 5.1.13 on 2025-10-12 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0007_rename_extra_reservaextra_servicios_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_cuenta',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='factura',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camping.reservaextra'),
        ),
    ]
