# Generated by Django 5.1.13 on 2025-10-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0008_alter_cliente_numero_cuenta_alter_factura_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
