# Generated by Django 5.1.13 on 2025-10-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0009_alter_cliente_numero_cuenta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='clientes',
            new_name='cliente',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
